name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: rustup target add wasm32-unknown-unknown
      - name: Install Leptos
        run: cargo install --locked cargo-leptos
      - name: Build
        run: cargo-leptos build
      - name: Run tests
        run: cargo-leptos test
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build Image'
        run: |
          docker build . --tag ghcr.io/welshdragon/dancing-hippo/test:latest
          docker push ghcr.io/welshdragon/dancing-hippo/test:latest
        
  
